app_university_student:
    resource: |
        path: university/students
        alias: app.university.student
        only:
            - index
            - show
        redirect: show
        grid: app_university_student
        vars:
            all:
                templates:
                    show: '@university/admin/student/show.html.twig'
    type: sylius.resource
